# This program finds the sum of the even-valued terms in in the Fibonacci sequence whose values do not exceed four million.

# the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...


max_range = 4 * (10**6) #maximum range

# Finding the summation
summation = 0 # The sume variable

n = 0
m = 1


while (m <= max_range):
    o = n + m
    if (o % 2 == 0):
        summation += o

    n = m
    m = o
    

print summation

    
    